version: '3'
services:
  openvpn:
    cap_add:
      - NET_ADMIN
    build: .
    image: ovpn_basic:1
    tty: true
    container_name: ovpn_basic
    ports:
      - "9010:1194/udp"
      - "9011:1080"
    #restart: unless-stopped
    volumes:
      - ./vpn:/etc/openvpn
      - ./sockd.conf:/etc/sockd.conf:ro
      - ./addSocksUsers.sh:/var/addSocksUsers.sh:ro
    dns:
      - 8.8.8.8
      - 8.8.4.4
    logging:
      driver: "json-file"
      options:
        max-size: "5mb"
        max-file: "3"
    #command: ["sh", "-c", "/var/addSocksUsers.sh && sockd && open_vpn"]
    #command: ["bash","-c", "sockd -D && /bin/local/open_vpn"]
    command: ["bash","-c", "sockd -D && ovpn_run"]
